{% set name = "PyVISA" %}
{% set version = "1.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 38247a5a3d49ea7add8a429d51d5229ab6559343af8ff77fc45fce26891391d3

build:
  number: 0
  entry_points:
    - pyvisa-info = pyvisa.cmd_line_tools:visa_info
    - pyvisa-shell = pyvisa.cmd_line_tools:visa_shell
  script:
    - "{{ PYTHON }} setup.py bdist_wheel --dist-dir=dist"
    - "{{ PYTHON }} -m pip install --find-links=dist --no-deps --ignore-installed --no-cache-dir -vvv {{ name }}"
  skip: True  # [py<36]

requirements:
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm
    - wheel
  run:
    - python
    - dataclasses  # [py<37]
    - importlib-metadata  # [py<38]
    - typing_extensions

test:
  imports:
    - visa
    - pyvisa
    - pyvisa.ctwrapper
    - pyvisa.resources
    - pyvisa.thirdparty
    - pyvisa.testsuite
  commands:
    - pip check
    - pyvisa-info
    - pyvisa-shell -h
  requires:
    - pip
    - pytest

about:
  home: https://github.com/hgrecco/pyvisa
  license: MIT
  license_file: LICENSE
  summary: Control your instruments with Python.
  description: |
    PyVISA is a Python package that enables you to control all kinds of measurement devices
    independently of the interface (e.g. GPIB, RS232, USB, Ethernet). As an example, reading
    self-identification from a Keithley Multimeter with GPIB number 12 is as easy as three
    lines of Python code:
  doc_url: https://pyvisa.readthedocs.io/
  dev_url: https://github.com/hgrecco/pyvisa

extra:
  recipe-maintainers:
    - melund
    - ddale
    - cjermain
    - MatthieuDartiailh
    - mtsolmn
