{% set name = "PyVISA" %}
{% set version = "1.9.1" %}
{% set sha256 = "d387dd215928bcc40f4ac21f1f344ca7a511ec3e8078f76876fa717174dbb993" %}

package:
  name: pyvisa
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0]|lower }}/{{ name|lower }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - setuptools
    - enum34  # [py<34]

test:
  imports:
    - visa

about:
  home: https://github.com/hgrecco/pyvisa
  license: MIT
  summary: Control your instruments with Python.
  description: |
    PyVISA is a Python package that enables you to control all kinds of measurement devices
    independently of the interface (e.g. GPIB, RS232, USB, Ethernet). As an example, reading
    self-identification from a Keithley Multimeter with GPIB number 12 is as easy as three
    lines of Python code:
  doc_url: https://pyvisa.readthedocs.io/
  dev_url: https://github.com/hgrecco/pyvisa

extra:
  recipe-maintainers:
    - melund
    - ddale
    - cjermain
    - MatthieuDartiailh
