appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: kYpjkgXRaUOSm9rxx9URo9ufFdFg/hVubaD2VIyxQJq/ShJ1+sVm+cdKXeH9rnC6TBej1cGzNQ2RYFlf34u0J9I7siHhSvs+cEakanfF2XOyDGOfXL0vJo8h9t+362bkOI8OhWFiiPiyumSFG1hyUHg2SmuEQOEArtkJPD8LqNTxTY61yvulypthy4hM8eAC7V+LOSvZBOlX5+G4VTu4jmhfx8PEj4qsIymz9mNHG3Jazpmz2RTyIHUNwtWOnXOv/PbJPAM07jpxyGJeV9vTLZD/z2l4q9gMibv8Nfcc5NXnFShgwMjhhsYC93bJzTgfK1p8rcy5yHsG/QARh0SK1wWpNNEi/7mCitTwdnAehO97qlQp9yAhSTh6GvRSUOGQepaNdRZuzabGMucCPL6Jzmt0w7+7zRP4pvszfSPm1nvFuyZcijpJXk3DgJOG0mBVWjiMKwcmLJjKOleUHizrSr4H10RGxAE91i4cI3bVhnDbk7ORIXZA8A8eeqeKlun8Uq6qHV8sF8rv3vetGMdqN5voVd8KHnN8sALF8q2llHH9fYu5WLBgmLjKRskyXA1dtCr0Qqo+DacFMB488ettt62zzbR0OW4SC0xgVvM6lmF0/LIwVyzpk7M6q3nVy+PvQgaMHF/72vn8gKI/Dt6bYnUepNXrp7fgBwu+88uYjQg=}
provider:
  win: azure
